name: dbt Analytics CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt & Databricks Adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-databricks

      - name: Setup dbt Profile Connections
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_TOKEN: ${{ secrets.DBT_TOKEN }}
          DBT_HTTP_PATH: ${{ secrets.DBT_HTTP_PATH }}
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          default:
            outputs:
              dev:
                type: databricks
                catalog: crypto_project_cat
                schema: default
                host: "${DBT_HOST}"
                http_path: "${DBT_HTTP_PATH}"
                token: "${DBT_TOKEN}"
                threads: 4
            target: dev
          EOF

      - name: Install dbt Packages
        run: |
          dbt deps

      - name: Run dbt Build (Models & Tests)
        run: |
          dbt build
